% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
clear
clc
a(1)=1;
a(2)=2;
k=2;
while a(k)<=4000000
    k=k+1;
    a(k)=a(k-1)+a(k-2); 
end
z=a(1:k-1);
disp(z);
m=0;
sumf=0;
r=rem(z,2);
for m=1:numel(z)
    if r(m)==0
        sumf=z(m)+sumf;
    end
end
disp(sumf);





    

